version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: widen
    commit-message:
      prefix: Chore
    labels:
      - npm
      - dependencies
      - automerge
      - autodelete
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: Chore
    labels:
      - github actions
      - dependencies
